# Generated by Django 5.2.7 on 2025-12-26 12:04

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('direcao', 'Direção'), ('secretaria', 'Secretaria'), ('professores', 'Professores'), ('funcionarios', 'Funcionários')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Cargo/Profissão')),
            ],
            options={
                'verbose_name': 'Cargo/Profissão',
                'verbose_name_plural': 'Cargo/Profissão',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/%Y/%m', verbose_name='Foto')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Excerto/Bibliografia')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(related_name='people', to='team.groups', verbose_name='Grupo a que pertence')),
                ('positions', models.ManyToManyField(related_name='peoples', to='team.positions', verbose_name='Cargo/Profissão')),
            ],
            options={
                'verbose_name': 'Corpo Docente e Não Docente',
                'verbose_name_plural': 'Corpo Docente e Não Docente',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=200, null=True, verbose_name='Área de Ensino')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='team.persons')),
            ],
            options={
                'verbose_name': 'Área de Ensino',
                'verbose_name_plural': 'Áreas de Ensino',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(blank=True, max_length=200, null=True, verbose_name='Experiência Profissional')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='team.persons')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiência Profissional',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Formação Académica')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='team.persons')),
            ],
            options={
                'verbose_name': 'Formação Académica',
                'verbose_name_plural': 'Formação Académica',
            },
        ),
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destaques Profissionais')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevances', to='team.persons')),
            ],
            options={
                'verbose_name': 'Destaque Profissional',
                'verbose_name_plural': 'Destaques Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Rede Social')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Rede Social')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='team.persons')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
    ]
