# Generated by Django 5.2.7 on 2026-02-04 12:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Experiência Profissional'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Área de Ensino'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Excerto/Bibliografia'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Formação Académica'),
        ),
        migrations.AlterField(
            model_name='relevance',
            name='relevance',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Destaques Profissionais'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nome da Rede Social'),
        ),
    ]
