# Generated by Django 5.2.7 on 2025-12-26 12:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Festival/%Y/%m', verbose_name='Imagem do Festival')),
                ('description', tinymce.models.HTMLField(verbose_name='Descrição do Evento')),
                ('address', models.CharField(max_length=100, verbose_name='Local de Realização')),
                ('begin_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Encerramento')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Informação')),
                ('link_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Link')),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festival',
            },
        ),
    ]
