# Generated by Django 5.2.7 on 2026-04-26 19:54

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_alter_festival_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Local de Realização'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Descrição do Evento'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
    ]
