# Generated by Django 5.2.7 on 2025-12-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='eventos/%Y/%m', verbose_name='Imagem do Evento')),
            ],
            options={
                'verbose_name': 'Eventos',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Evento')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Realização')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='event.event')),
            ],
        ),
    ]
