# Generated by Django 5.2.7 on 2026-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='local',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Local de Realização'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Evento'),
        ),
    ]
