# Generated by Django 5.2.7 on 2026-02-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventdetails_local_alter_eventdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='date',
            field=models.CharField(blank=True, default='', help_text='Ex: 00/00/0000 às 00h00', max_length=100, verbose_name='Data e Hora'),
        ),
    ]
