# Generated by Django 5.2.7 on 2026-02-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventdetails_date_alter_eventdetails_local_and_more'),
        ('event', '0003_alter_eventdetails_date'),
    ]

    operations = [
    ]
