# Generated by Django 5.2.7 on 2026-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_merge_20260204_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='date',
            field=models.CharField(blank=True, default='', help_text='Ex: 00/00/0000 às 00h00', max_length=100, verbose_name='Data e Hora'),
        ),
    ]
