# Generated by Django 5.2.7 on 2026-02-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_options_alter_eventdetails_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
    ]
