# Generated by Django 5.2.7 on 2026-03-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
    ]
