# Generated by Django 5.2.7 on 2025-12-26 12:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPenamacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', tinymce.models.HTMLField(verbose_name='Morada')),
                ('contact', models.CharField(help_text="Exemplo: '+351 000 000 000'", max_length=100, verbose_name='Telefone/Telemóvel')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('time', models.CharField(help_text="Exemplo: 'Seg a Sex - 08h00 às 21h00'", max_length=150, verbose_name='Horário de Funcionamento')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('direcao', 'Direção'), ('coordenacao', 'Coordenação'), ('professores', 'Professores'), ('funcionarios', 'Funcionários')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Cargo/Profissão')),
            ],
            options={
                'verbose_name': 'Cargo/Profissão',
                'verbose_name_plural': 'Cargo/Profissão',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='polo/%Y/%m', verbose_name='Foto')),
                ('groups', models.ManyToManyField(related_name='people', to='polo.group', verbose_name='Grupo a que pertence')),
                ('positions', models.ManyToManyField(related_name='people', to='polo.position', verbose_name='Cargo/Profissão')),
            ],
            options={
                'verbose_name': 'Corpo Docente e Não Docente',
                'verbose_name_plural': 'Corpo Docente e Não Docente',
            },
        ),
    ]
