# Generated by Django 5.2.7 on 2026-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpenamacor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=150, verbose_name='Email'),
        ),
    ]
