# Generated by Django 5.2.7 on 2025-12-26 12:04

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=100, verbose_name='Título Página Principal')),
                ('short_description', tinymce.models.HTMLField(verbose_name='Descrição curta sobre a Academia')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m', verbose_name='Primeira Imagem')),
                ('title_2', models.CharField(blank=True, max_length=100, verbose_name='Título Página do Sobre')),
                ('long_description', tinymce.models.HTMLField(verbose_name='Descrição longa sobre a Academia')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m', verbose_name='Segunda Imagem')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m', verbose_name='Terceira Imagem')),
            ],
            options={
                'verbose_name': 'Sobre a Academia',
                'verbose_name_plural': 'Sobre a Academia',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto Alusivo aos Cursos')),
                ('course_name_2', models.CharField(max_length=100, verbose_name='Título para Detalhes')),
                ('portaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Portaria / Decreto-Lei')),
                ('instruments', tinymce.models.HTMLField(verbose_name='Composição do Curso')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m', verbose_name='Imagem do Site')),
                ('academia_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Academia')),
                ('short_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frase Alusiva')),
            ],
            options={
                'verbose_name': 'Página Inicial',
                'verbose_name_plural': 'Página Inicial',
            },
        ),
        migrations.CreateModel(
            name='DevLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Dev')),
            ],
            options={
                'verbose_name': 'Link do Dev',
                'verbose_name_plural': 'Link do Dev',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Ficheiro')),
                ('link', models.URLField(max_length=500, verbose_name='Link do Ficheiro')),
            ],
            options={
                'verbose_name': 'Downloads',
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_amdf', models.ImageField(blank=True, null=True, upload_to='logos_rodapé/%Y/%m', verbose_name='Logo AMDF')),
                ('logo_sc', models.ImageField(blank=True, null=True, upload_to='logos_rodapé/%Y/%m', verbose_name='Logo Santa Casa')),
                ('logo_ed', models.ImageField(blank=True, null=True, upload_to='logos_rodapé/%Y/%m', verbose_name='Logo Educação')),
                ('link_facebook', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Facebook')),
                ('link_instagram', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Instagram')),
                ('address', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Morada')),
                ('contact', models.CharField(blank=True, help_text="Exemplo: '+351 000 000 000'", max_length=100, null=True, verbose_name='Telemóvel/Telefone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('time', models.CharField(blank=True, help_text="Exemplo: 'Seg a Sex - 08h00 às 21h00'", max_length=100, null=True, verbose_name='Horário de Funcionamento')),
            ],
            options={
                'verbose_name': 'Rodapé',
                'verbose_name_plural': 'Rodapé',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome da Galeria')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galeria',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Ficheiro')),
                ('link', models.URLField(max_length=500, verbose_name='Link do Ficheiro')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='LogoNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_navbar/%Y/%m', verbose_name='Logo Página Inicial')),
            ],
            options={
                'verbose_name': 'Logo Barra de Navegação',
                'verbose_name_plural': 'Logo Barra de Navegação',
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Imagem ou Vídeo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galeria/imagem/%Y/%m', verbose_name='Imagem')),
                ('video', models.FileField(blank=True, null=True, upload_to='galeria/videos/%Y/%m', verbose_name='Vídeo')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='amdf.gallery')),
            ],
        ),
    ]
