# Generated by Django 5.2.7 on 2026-01-19 20:16

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Título Página do Sobre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='portaria',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Portaria / Decreto-Lei'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Texto Alusivo aos Cursos'),
        ),
        migrations.AlterField(
            model_name='coverpage',
            name='academia_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da Academia'),
        ),
        migrations.AlterField(
            model_name='coverpage',
            name='short_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Frase Alusiva'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Morada'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact',
            field=models.CharField(blank=True, default='', help_text="Exemplo: '+351 000 000 000'", max_length=100, verbose_name='Telemóvel/Telefone'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='time',
            field=models.CharField(blank=True, default='', help_text="Exemplo: 'Seg a Sex - 08h00 às 21h00'", max_length=100, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da Imagem ou Vídeo'),
        ),
    ]
