# Generated by Django 5.2.7 on 2026-03-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amdf', '0002_alter_about_title_2_alter_course_portaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='midia',
            options={'ordering': ['-id']},
        ),
    ]
