# Generated by Django 5.2.7 on 2026-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amdf', '0003_alter_gallery_options_alter_midia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='link_youtube',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do youtube'),
        ),
    ]
